name: PR Validation

on:
  pull_request:
    branches:
      - stag
      - prod

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
